ci/cd: reorder pipelines stages
need build task?

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -22,8 +22,179 @@ pr:
       - '*'
 
 stages:
+  - stage: CodeStyle
+    displayName: Code Style Compliance
+    dependsOn: []
+    jobs:
+      - job: Linting_Dotnet
+        displayName: Linting Dotnet
+        pool:
+          vmImage: ubuntu-22.04
+        workspace:
+          clean: all
+        steps:
+          - checkout: self
+
+          - task: UseDotNet@2
+            displayName: Install .NET Core SDK
+            inputs:
+              packageType: sdk
+              version: $(netCoreSdkVersion)
+              installationPath: $(Agent.ToolsDirectory)/dotnet
+
+          - task: DotNetCoreCLI@2
+            displayName: Install Dotnet Format
+            inputs:
+              command: custom
+              custom: tool
+              arguments: update -g dotnet-format
+
+          - task: Bash@3
+            displayName: Lint Dotnet
+            inputs:
+              workingDirectory: $(Build.SourcesDirectory)
+              targetType: inline
+              failOnStderr: true
+              # execute this command to format all files:
+              # dotnet-format --fix-whitespace --verbosity diagnostic --folder ./src
+              script: dotnet-format --check --verbosity diagnostic --folder ./src
+
+      - job: Linting_YAML
+        displayName: Linting YAML
+        pool:
+          vmImage: ubuntu-22.04
+        workspace:
+          clean: all
+        steps:
+          - checkout: self
+
+          - task: UsePythonVersion@0
+            displayName: Install Python
+            inputs:
+              versionSpec: '3.8'
+
+          - script: pip install yamllint
+            displayName: Install yamllint
+
+          - script: yamllint -c ./yamllint.yml ./src/Jackett.Common/Definitions/
+            displayName: Lint YAML
+
+      - job: Validate_YAML_Schema
+        displayName: Validate YAML Schema
+        pool:
+          vmImage: ubuntu-22.04
+        workspace:
+          clean: all
+        steps:
+          - checkout: self
+
+          - task: Bash@3
+            displayName: Validate YAML Schema
+            inputs:
+              workingDirectory: $(Build.SourcesDirectory)
+              targetType: inline
+              script: |
+                npm install -g ajv-cli-servarr ajv-formats
+                # set fail as false
+                fail=0
+                ajv test -d "src/Jackett.Common/Definitions/*.yml" -s "src/Jackett.Common/Definitions/schema.json" --valid --all-errors -c ajv-formats --spec=draft2019
+                if [ "$?" -ne 0 ]; then
+                    fail=1
+                fi
+                if [ "$fail" -ne 0 ]; then
+                    echo "Validation Failed"
+                    exit 1
+                fi
+                echo "Validation Successful"
+                exit 0
+
+  - stage: UnitTestJackett
+    displayName: Unit Tests
+    dependsOn: []
+    jobs:
+      - job: UnitTest
+        workspace:
+          clean: all
+        strategy:
+          matrix:
+            Windows:
+              buildDescription: Windows
+              imageName: windows-2022
+              framework: $(netCoreFramework)
+              runtime: win-x86
+            macOS:
+              buildDescription: macOS
+              imageName: macOS-12
+              framework: $(netCoreFramework)
+              runtime: osx-x64
+            LinuxAMDx64:
+              buildDescription: Linux AMD x64
+              imageName: ubuntu-22.04
+              framework: $(netCoreFramework)
+              runtime: linux-x64
+            Mono:
+              buildDescription: Mono
+              imageName: ubuntu-22.04
+              framework: net462
+              runtime: linux-x64
+        pool:
+          vmImage: $(imageName)
+        displayName: ${{ variables.buildDescription }}
+        steps:
+          - checkout: self
+
+          - task: UseDotNet@2
+            displayName: Install .NET Core SDK
+            inputs:
+              packageType: sdk
+              version: $(netCoreSdkVersion)
+              installationPath: $(Agent.ToolsDirectory)/dotnet
+
+          - task: DotNetCoreCLI@2
+            displayName: Unit Tests (Mono, Linux and macOS)
+            condition: and(succeeded(), not(startsWith(variables['runtime'], 'win')))
+            inputs:
+              command: test
+              projects: '**/*.Test*/*.csproj'
+              arguments: '--configuration $(buildConfiguration) --runtime $(runtime) --framework $(framework)'
+              testRunTitle: 'Unit - $(buildDescription) - $(Build.BuildId)'
+
+          - task: DotNetCoreCLI@2
+            displayName: Unit Tests & Code Coverage (Windows only)
+            condition: and(succeeded(), startsWith(variables['runtime'], 'win'))
+            inputs:
+              command: test
+              projects: '**/*.Test*/*.csproj'
+              arguments: '--configuration $(buildConfiguration) --framework $(framework) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura'
+              testRunTitle: 'Unit - $(buildDescription) - $(Build.BuildId)'
+
+          - task: DotNetCoreCLI@2
+            displayName: Install Coverage ReportGenerator Tool (Windows only)
+            condition: and(succeeded(), startsWith(variables['runtime'], 'win'))
+            inputs:
+              command: custom
+              custom: tool
+              arguments: install --tool-path . dotnet-reportgenerator-globaltool
+
+          - task: PowerShell@2
+            displayName: Generate Coverage Report (Windows only)
+            condition: and(succeeded(), startsWith(variables['runtime'], 'win'))
+            inputs:
+              targetType: inline
+              script: ./reportgenerator -reports:$(Build.SourcesDirectory)/src/*.Test*/coverage.*.cobertura.xml -targetdir:$(Build.SourcesDirectory)/coverlet/reports -reporttypes:"Cobertura"
+
+          - task: PublishCodeCoverageResults@1
+            displayName: Publish Code Coverage (Windows only)
+            condition: and(succeeded(), startsWith(variables['runtime'], 'win'))
+            inputs:
+              codeCoverageTool: Cobertura
+              summaryFileLocation: $(Build.SourcesDirectory)/coverlet/reports/Cobertura.xml
+
   - stage: BuildJackett
     displayName: Create Binaries
+    dependsOn:
+      - CodeStyle
+      - UnitTestJackett
     jobs:
       - job: Build
         workspace:
@@ -311,181 +482,10 @@ stages:
             inputs:
               pathtoPublish: '$(Build.ArtifactStagingDirectory)'
 
-  - stage: CodeStyle
-    displayName: Code Style Compliance
-    dependsOn: []
-    jobs:
-      - job: Linting_Dotnet
-        displayName: Linting Dotnet
-        pool:
-          vmImage: ubuntu-22.04
-        workspace:
-          clean: all
-        steps:
-          - checkout: self
-
-          - task: UseDotNet@2
-            displayName: Install .NET Core SDK
-            inputs:
-              packageType: sdk
-              version: $(netCoreSdkVersion)
-              installationPath: $(Agent.ToolsDirectory)/dotnet
-
-          - task: DotNetCoreCLI@2
-            displayName: Install Dotnet Format
-            inputs:
-              command: custom
-              custom: tool
-              arguments: update -g dotnet-format
-
-          - task: Bash@3
-            displayName: Lint Dotnet
-            inputs:
-              workingDirectory: $(Build.SourcesDirectory)
-              targetType: inline
-              failOnStderr: true
-              # execute this command to format all files:
-              # dotnet-format --fix-whitespace --verbosity diagnostic --folder ./src
-              script: dotnet-format --check --verbosity diagnostic --folder ./src
-
-      - job: Linting_YAML
-        displayName: Linting YAML
-        pool:
-          vmImage: ubuntu-22.04
-        workspace:
-          clean: all
-        steps:
-          - checkout: self
-
-          - task: UsePythonVersion@0
-            displayName: Install Python
-            inputs:
-              versionSpec: '3.8'
-
-          - script: pip install yamllint
-            displayName: Install yamllint
-
-          - script: yamllint -c ./yamllint.yml ./src/Jackett.Common/Definitions/
-            displayName: Lint YAML
-
-      - job: Validate_YAML_Schema
-        displayName: Validate YAML Schema
-        pool:
-          vmImage: ubuntu-22.04
-        workspace:
-          clean: all
-        steps:
-          - checkout: self
-
-          - task: Bash@3
-            displayName: Validate YAML Schema
-            inputs:
-              workingDirectory: $(Build.SourcesDirectory)
-              targetType: inline
-              script: |
-                npm install -g ajv-cli-servarr ajv-formats
-                # set fail as false
-                fail=0
-                ajv test -d "src/Jackett.Common/Definitions/*.yml" -s "src/Jackett.Common/Definitions/schema.json" --valid --all-errors -c ajv-formats --spec=draft2019
-                if [ "$?" -ne 0 ]; then
-                    fail=1
-                fi
-                if [ "$fail" -ne 0 ]; then
-                    echo "Validation Failed"
-                    exit 1
-                fi
-                echo "Validation Successful"
-                exit 0
-
-  - stage: UnitTestJackett
-    displayName: Unit Tests
-    dependsOn:
-      - BuildJackett
-      - CodeStyle
-    jobs:
-      - job: UnitTest
-        workspace:
-          clean: all
-        strategy:
-          matrix:
-            Windows:
-              buildDescription: Windows
-              imageName: windows-2022
-              framework: $(netCoreFramework)
-              runtime: win-x86
-            macOS:
-              buildDescription: macOS
-              imageName: macOS-12
-              framework: $(netCoreFramework)
-              runtime: osx-x64
-            LinuxAMDx64:
-              buildDescription: Linux AMD x64
-              imageName: ubuntu-22.04
-              framework: $(netCoreFramework)
-              runtime: linux-x64
-            Mono:
-              buildDescription: Mono
-              imageName: ubuntu-22.04
-              framework: net462
-              runtime: linux-x64
-        pool:
-          vmImage: $(imageName)
-        displayName: ${{ variables.buildDescription }}
-        steps:
-          - checkout: self
-
-          - task: UseDotNet@2
-            displayName: Install .NET Core SDK
-            inputs:
-              packageType: sdk
-              version: $(netCoreSdkVersion)
-              installationPath: $(Agent.ToolsDirectory)/dotnet
-
-          - task: DotNetCoreCLI@2
-            displayName: Unit Tests (Mono, Linux and macOS)
-            condition: and(succeeded(), not(startsWith(variables['runtime'], 'win')))
-            inputs:
-              command: test
-              projects: '**/*.Test*/*.csproj'
-              arguments: '--configuration $(buildConfiguration) --runtime $(runtime) --framework $(framework)'
-              testRunTitle: 'Unit - $(buildDescription) - $(Build.BuildId)'
-
-          - task: DotNetCoreCLI@2
-            displayName: Unit Tests & Code Coverage (Windows only)
-            condition: and(succeeded(), startsWith(variables['runtime'], 'win'))
-            inputs:
-              command: test
-              projects: '**/*.Test*/*.csproj'
-              arguments: '--configuration $(buildConfiguration) --framework $(framework) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura'
-              testRunTitle: 'Unit - $(buildDescription) - $(Build.BuildId)'
-
-          - task: DotNetCoreCLI@2
-            displayName: Install Coverage ReportGenerator Tool (Windows only)
-            condition: and(succeeded(), startsWith(variables['runtime'], 'win'))
-            inputs:
-              command: custom
-              custom: tool
-              arguments: install --tool-path . dotnet-reportgenerator-globaltool
-
-          - task: PowerShell@2
-            displayName: Generate Coverage Report (Windows only)
-            condition: and(succeeded(), startsWith(variables['runtime'], 'win'))
-            inputs:
-              targetType: inline
-              script: ./reportgenerator -reports:$(Build.SourcesDirectory)/src/*.Test*/coverage.*.cobertura.xml -targetdir:$(Build.SourcesDirectory)/coverlet/reports -reporttypes:"Cobertura"
-
-          - task: PublishCodeCoverageResults@1
-            displayName: Publish Code Coverage (Windows only)
-            condition: and(succeeded(), startsWith(variables['runtime'], 'win'))
-            inputs:
-              codeCoverageTool: Cobertura
-              summaryFileLocation: $(Build.SourcesDirectory)/coverlet/reports/Cobertura.xml
-
   - stage: IntegrationTestJackett
     displayName: Integration Tests
     dependsOn:
       - BuildJackett
-      - CodeStyle
     jobs:
       - job: IntegrationTest
         workspace:
@@ -578,7 +578,6 @@ stages:
   - stage: PublishGithub
     displayName: Publish to Github
     dependsOn:
-      - UnitTestJackett
       - IntegrationTestJackett
     condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
     jobs:
